### ISSUE TITLE
Replacement of Bugfender.getDeviceIdentifier()

### ISSUE THREAD

**Issue by manishpatelgt** [bugfender/BugfenderSDK-android-sample#12]
Provide me information regarding 
   
  ```
   String deviceIdentifier = Bugfender.getDeviceIdentifier();
   Bugfender.d("DEBUG", "Device identifier: " + deviceIdentifier);
```
I am using below version in my Android Studio

`  implementation 'com.bugfender.sdk:android:1.+'`

As I see this method is deprecated.

**Comment by jgimenez** [comment]
Hi @manishpatelgt , as the docs indicate, you can use `getDeviceUrl()` instead, which will give you an URL that points to that device. You can use that URL to link Bugfender with your own platform or other services you might be using

**Comment by manishpatelgt** [comment]
@jgimenez Thanks Jordi
