### ISSUE TITLE
Propagating Bugfender logs to Logcat 

### ISSUE THREAD

**Issue by abdelhameedo** [bugfender/BugfenderSDK-android-sample#14]
I am using com.bugfender.sdk:android:3.0.8
 
I have added many Bugfender.d(tag,"<Somthing>") logs to a specific part of project .

for initialization I have added the following code to myApp class 

 ```
Bugfender.init(this, "<My Key>", BuildConfig.DEBUG);
 Bugfender.enableCrashReporting();
 Bugfender.enableUIEventLogging(this);
```

When I run the project in debug I have noticed that the logs are shown correctly in the bugfender portal . but they are not appearing in my logcat , I have observed the internal code of the bugfender and I have noticed that in debug mode it should propagate the logs to the logcat but this is not the case . 

I have noticed  the method "enableLogcatLogging" but this will send all the logs to the portal which is not needed 

Is there a way to achieve this  ? 

Thanks

**Comment by jgimenez** [comment]
Hi there, the third parameter to the init call is indicating if you want logs to be sent to logcat. We usually recommend to use the build configuration flag, but you can definitely change it to true if you prefer.

**Comment by abdelhameedo** [comment]
thanks @jgimenez
