### ISSUE TITLE
Disable Bugfender

### ISSUE THREAD

**Issue by alevittoria** [bugfender/BugfenderSDK-android-sample#17]
I want to know how to disable Bugfender after a standard initialization, could anyone help me?

**Comment by jgimenez** [comment]
Hi there, Bugfender can not be disabled after initialization.

However, why do you want to do that? You likely don't need to. You can, for example, control the logs sent by using a logging framework. If you'd like to discuss this further a solution for your specific needs, you can contact us at support.bugfender.com.

**Comment by alevittoria** [comment]
@jgimenez I want to be able to disable all kinds of analytics if the user doesn't give me permission.
I have done something like this at the moment:

```kotlin
Bugfender.init(application, key, BuildConfig.DEBUG)
Bugfender.enableCrashReporting()
Bugfender.enableUIEventLogging(application)
Bugfender.enableLogcatLogging(LogcatInterceptor { interceptedLog ->
    if (!sendLogs) {
        return@LogcatInterceptor null
    interceptedLog
})
```

But I can't disable crashReporting and UIEventLogging in this way
