### ISSUE TITLE
Not working in Foreground service after activity is destroyed

### ISSUE THREAD

**Issue by indiandragon** [bugfender/BugfenderSDK-android-sample#2]
Hi Bugfender team,

I have been using Bugfender for a while now & I can confirm that there is an issue related to usage in foreground services in Android.

Steps : 
1.  Include Bugfender sdk in Application class as advised by the document.
2. Implement a Foreground service (Service with notification) & print random logs continuously .
3. Put the display to sleep [To make sure the activity is destroyed] .

Logs will be available in Bugfender console only till the screen was awake i.e when activity was alive. Technically , application is alive as the service is active & Bugfender is supposed to work in services.

Let me know if any further details is needed, fixing this would enable bugfender to be used in services of apps where user intervention is not available & where bug fender would be really helpful.

**Comment by jgimenez** [comment]
Hi @indiandragon . I'm sorry you're experiencing trouble. Thanks for the detailed report, we'll try to reproduce it (if you could attach a sample project that would be even better).

My only suspicion for now would be that for some reason the foreground service is actually dying and restarting. If all activities/services/... of the application are destroyed that would destroy the process and create a new Bugfender session upon restart. We would need to check that. Could you please point me to a sample session ID where this is happening? Thanks.

**Comment by indiandragon** [comment]
Hi @jgimenez I will check and revert the same asap.
