### ISSUE TITLE
NPE in bugfender sdk

### ISSUE THREAD

**Issue by AlexZvonik** [bugfender/BugfenderSDK-android-sample#4]
```
Fatal Exception: java.lang.NullPointerException
       at com.bugfender.sdk.a.a.l.a.b(Unknown Source)
       at com.bugfender.sdk.a.a.b$4.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:864)
```

**Comment by jgimenez** [comment]
Hi, which version are you using?

**Comment by AlexZvonik** [comment]
@jgimenez 
Hey,
The last one :-)
`compile 'com.bugfender.sdk:android:0.+'`

**Comment by jgimenez** [comment]
Hi @AlexZvonik , it looks like for some reason you are not using the latest version. Could you please replace the configuration line to this?
`compile 'com.bugfender.sdk:android:0.7.7'`

**Comment by AlexZvonik** [comment]
Ok, thanks.
Now my app use the latest version. But i have to upload my app to the market and check whether users will report crashes related to bugfender.

**Comment by jgimenez** [comment]
OK, good, Alex. Please let us know if it's still an issue. Closing for now.
