### ISSUE TITLE
Android logs/crashes not appearing.

### ISSUE THREAD

**Issue by marksheekey** [bugfender/BugfenderSDK-android-sample#6]
Hello, 
I assume I'm using the latest version, my gradle entry is this..
compile 'com.bugfender.sdk:android:1.+'

I was expecting that when someone has a crash then that would be logged, with a crash report. 
(I have all devices disabled, but thought crashes logged nevertheless)
Unfortunately I',, not getting anything.

Cheers,
Mark

**Comment by jgimenez** [comment]
Hi Mark, this is exactly what should happen. I recommend you to contact us over the support chat and we will check if there is something wrong with your account.
