### ISSUE TITLE
Bugfender SDK: Network error, will retry later

### ISSUE THREAD

**Issue by LSDsl** [bugfender/BugfenderSDK-android-sample#9]
See in log many times
```Bugfender SDK: Network error, will retry later```
and no logs in web console

SDK 1.0.7

**Comment by smithaaron** [comment]
Me too. Console is also very slow. I'm assuming they're having server issues.

Had just signed up last week and was planning to upgrade to a paid account, but not so sure now if this is representative of the reliability.

**Comment by jgimenez** [comment]
Sorry for the trouble, we had an outage on one of our servers and are currently working on it. We are posting updates on https://status.bugfender.com/
